POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mstitane",
  "name": "Mohammed STITANE",
  "password": "123"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "name user 2",
  "password": "123"
}

###
GET http://localhost:3003/api/users
Accept: application/json
